# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
solc = "0.8.24"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]
eth_rpc_url="http://127.0.0.1:8545"

[fmt]
# [fmt]: code formatter options for `forge fmt`.
# These control formatting behavior such as bracket spacing, preferred quote style,
# line length, and other stylistic preferences applied during formatting.
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[lint]
# ... rest of lint config ...
exclude_lints = ["unused-import"]
lint_on_build = false
severity = ["Gas"]
